#!/usr/bin/env bash

if [ "$#" -lt 4 ]; then
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

FILE=$1
SERVER=$2
USER=$3
SSH_KEY=$4

Transfer the file using SCP
scp -o StrictHostKeyChecking=no -i $SSH_KEY $FILE $USER@$SERVER:~/

Check if the transfer was successful
if [ "$?" -ne 0 ]; then
echo "Error: Failed to transfer the file."
exit 1
fi

echo "File transfer completed successfully."
