#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt update
sudo apt install nginx -y

# Add custom HTTP response header to Nginx configuration file
sudo sed -i '/server {/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

